---
formatter: markdown document

output:
  file: "README.md"
  mode: inject
  template: |-
    [//]: # ( BEGIN_TF_DOCS )

    {{ .Content }}

    [//]: # ( END_TF_DOCS )

output-values:
  enabled: false
  from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show:
    - all
#    - data-sources
#    - footer
#    - header
#    - inputs
#    - modules
#    - outputs
#    - providers
#    - requirements
#    - resources

settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: false
  hide-empty: true
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: required

version: ">= 0.16.0, < 1.0.0"
